const ROOT = {
	USER: '/User',
	SERVICE: '/Service',
	SUBSERVICE: '/Subservice',
	VENDOR: '/Vendor',
	BOOKING: '/Booking',
	ENHANCED_BOOKING: '/bookings',
	OTP: '/otp',
	NOTIFICATION: '/notification',
	REVIEW: '/reviews',
	SUBSCRIPTION: '/subscription',
	DASHBOARD: '/dashboard',
	ADMIN: '/admin',
	SHIFT_AVAILABILITY: '/shift-availability',
} as const;

export const API_ENDPOINTS = {
	auth: {
		login: `${ROOT.USER}/Login`,
		register: `${ROOT.USER}/InsertUser`,
		logout: `${ROOT.USER}/Logout`,
		validateToken: `${ROOT.USER}/validate-token`,
		forgotPassword: `${ROOT.USER}/forgot-password`,
		resetPassword: `${ROOT.USER}/reset-password`,
		verifyResetToken: `${ROOT.USER}/verify-reset-token`,
		verifyEmail: `${ROOT.USER}/verify-email`,
		resendVerification: `${ROOT.USER}/resend-verification`,
		changePassword: `${ROOT.USER}/changePassword`,
	},
	profile: {
		get: `${ROOT.USER}/mobile-profile`,
		update: `${ROOT.USER}/mobile-profile`,
	},
	service: {
		all: `${ROOT.SERVICE}/GetAllServices`,
		byId: (serviceId: number | string) => `${ROOT.SERVICE}/GetServiceById/${serviceId}`,
		subservicesByCategory: (serviceCategoryId: number | string) =>
			`${ROOT.SERVICE}/GetSubservicesByServiceCategoryId/${serviceCategoryId}`,
	},
	vendor: {
		all: `${ROOT.VENDOR}/Getallvendors`,
		profile: `${ROOT.VENDOR}/GetVendorProfile`,
		profileById: `${ROOT.VENDOR}/getvendorById`,
		createProfile: `${ROOT.VENDOR}/InsertVendor`,
		updateProfile: `${ROOT.VENDOR}/updateVendorProfile`,
		kpis: `${ROOT.VENDOR}/GetVendorKPIs`,
		activities: `${ROOT.VENDOR}/GetVendorRecentActivities`,
		byService: `${ROOT.VENDOR}/getvendorsByServiceId`,
		bySubservice: `${ROOT.VENDOR}/getvendorsBysubserviceId`,
		shifts: `${ROOT.VENDOR}/getVendorShiftforVendor`,
		createShift: `${ROOT.VENDOR}/AddvendorShifts`,
		updateShift: `${ROOT.VENDOR}/updateVendorShiftbyId`,
		deleteShift: `${ROOT.VENDOR}/deleteVendorShiftbyId`,
		packages: `${ROOT.VENDOR}/getAllVendorPackages`,
		createPackage: `${ROOT.VENDOR}/insertVendorPackage`,
		updatePackage: `${ROOT.VENDOR}/updateVendorPackage`,
		deletePackage: `${ROOT.VENDOR}/deleteVendorPackage`,
		eventImages: `${ROOT.VENDOR}/GetvendorEventImages`,
		uploadEventImages: `${ROOT.VENDOR}/AddEventImages`,
		deleteEventImage: `${ROOT.VENDOR}/DeleteEventImage`,
	},
	booking: {
		create: `${ROOT.BOOKING}/InsertBooking`,
		listByUser: `${ROOT.BOOKING}/GetBookingsByUserId`,
		listByVendor: `${ROOT.BOOKING}/GetBookingsByVendorId`,
		byId: (bookingId: number | string) => `${ROOT.BOOKING}/GetBookingById/${bookingId}`,
		cancelLegacy: (bookingId: number | string) => `${ROOT.BOOKING}/DeleteBooking/${bookingId}`,
		enhancedCreate: `${ROOT.ENHANCED_BOOKING}/`,
		accept: (bookingId: number | string) => `${ROOT.ENHANCED_BOOKING}/${bookingId}/accept`,
		reject: (bookingId: number | string) => `${ROOT.ENHANCED_BOOKING}/${bookingId}/reject`,
		approve: (bookingId: number | string) => `${ROOT.ENHANCED_BOOKING}/${bookingId}/approve`,
		adminReject: (bookingId: number | string) => `${ROOT.ENHANCED_BOOKING}/${bookingId}/admin-reject`,
		cancel: (bookingId: number | string) => `${ROOT.ENHANCED_BOOKING}/${bookingId}/cancel`,
	},
	otp: {
		generate: `${ROOT.OTP}/generate`,
		verify: `${ROOT.OTP}/verify`,
		resend: `${ROOT.OTP}/resend`,
		status: (bookingId: number | string) => `${ROOT.OTP}/${bookingId}/status`,
		attempts: (bookingId: number | string) => `${ROOT.OTP}/${bookingId}/attempts`,
	},
	notification: {
		all: `${ROOT.NOTIFICATION}/`,
		unreadCount: `${ROOT.NOTIFICATION}/count/unread`,
		markRead: (notificationId: number | string) => `${ROOT.NOTIFICATION}/${notificationId}/read`,
		markAllRead: `${ROOT.NOTIFICATION}/mark-all-read`,
		archive: (notificationId: number | string) => `${ROOT.NOTIFICATION}/${notificationId}/archive`,
		delete: (notificationId: number | string) => `${ROOT.NOTIFICATION}/${notificationId}`,
	},
	review: {
		submitAuthenticated: (bookingId: number | string) => `${ROOT.REVIEW}/bookings/${bookingId}`,
		submitWithToken: `${ROOT.REVIEW}/submit-with-token`,
		vendorReviews: (vendorId: number | string) => `${ROOT.REVIEW}/vendor/${vendorId}`,
		vendorAverageRating: (vendorId: number | string) =>
			`${ROOT.REVIEW}/vendor/${vendorId}/rating/average`,
		canReview: (bookingId: number | string) => `${ROOT.REVIEW}/bookings/${bookingId}/can-review`,
		recent: `${ROOT.REVIEW}/recent`,
		topVendors: `${ROOT.REVIEW}/top-vendors`,
	},
	subscription: {
		createOrder: `${ROOT.SUBSCRIPTION}/create-order`,
		verifyPayment: `${ROOT.SUBSCRIPTION}/verify-payment`,
		status: `${ROOT.SUBSCRIPTION}/status`,
		all: `${ROOT.SUBSCRIPTION}/all`,
		testActivate: `${ROOT.SUBSCRIPTION}/test-activate`,
	},
	dashboard: {
		userKpis: `${ROOT.DASHBOARD}/user/kpis`,
		userMonthly: `${ROOT.DASHBOARD}/user/monthly`,
		adminKpis: `${ROOT.ADMIN}/dashboard/kpis`,
		adminActivities: `${ROOT.ADMIN}/dashboard/activities`,
		adminAnalytics: `${ROOT.ADMIN}/dashboard/analytics`,
	},
	shiftAvailability: {
		availableShifts: `${ROOT.SHIFT_AVAILABILITY}/available-shifts`,
		checkShift: `${ROOT.SHIFT_AVAILABILITY}/check-shift`,
		calendar: `${ROOT.SHIFT_AVAILABILITY}/calendar`,
	},
	manualReservations: {
		create: '/manual-reservations',
		listByVendor: (vendorId: number | string) => `/manual-reservations/vendor/${vendorId}`,
		cancel: (reservationId: number | string) => `/manual-reservations/${reservationId}`,
	},
} as const;

export type ApiEndpoints = typeof API_ENDPOINTS;
