import { Platform } from "react-native";

export const AppPalettes = {
  light: {
    // primary: '#4B2FA8',
    // primaryStrong: '#3A1E7F',
    // accent: '#E9C46A',
    // rose: '#E8809F',
    // roseSoft: '#FCEAF0',
    // screenBg: '#F5F2FF',
    // surfaceBg: '#FFFFFF',
    // elevatedBg: '#EEE8FF',
    // border: '#DCCFFF',
    // text: '#1A1A2E',
    // subtext: '#56566E',
    // muted: '#8D87A8',
    // pressedBg: '#E4DBFF',
    // headerBtnBg: '#F0EAFF',
    // switchOn: '#4B2FA8',
    // switchOff: '#CBBEEB',
    // tint: '#4B2FA8',
    // onPrimary: '#FFFFFF',
    // danger: '#BA1A1A',
    // dangerSoft: '#FDECEC',
    // dangerBorder: '#F8C9C9',
    // success: '#2C7A4B',
    // successSoft: '#E8F7EE',
    // successBorder: '#B7E2C7',
    // info: '#245D87',
    // infoSoft: '#E8F2FA',
    // infoBorder: '#BCD4E8',
    // warning: '#A05D11',
    // warningSoft: '#FFF3E3',
    // overlay: 'rgba(8, 18, 34, 0.42)',
    // shadow: '#1A1A2E',

    // light palette — Rose & Champagne
    primary: "#C0326B",
    primaryStrong: "#8B1A4A",
    accent: "#E8B4A0",
    rose: "#E8809F",
    roseSoft: "#FCEAF0",
    screenBg: "#FFF5F8",
    surfaceBg: "#FFFFFF",
    elevatedBg: "#FFE8F0",
    border: "#F0C0D4",
    text: "#2A0D1C",
    subtext: "#7A4060",
    muted: "#B07090",
    pressedBg: "#FADADF",
    headerBtnBg: "#F9E2EC",
    icon: "#7A4060",
    onPrimary: "#FFFFFF",
    tint: "#C0326B",
    danger: "#B91C1C",
    dangerSoft: "#FDECEC",
    dangerBorder: "#F8C9C9",
    success: "#2E7D55",
    successSoft: "#E8F7EE",
    successBorder: "#B7E2C7",
    info: "#1E6FA8",
    infoSoft: "#E8F2FA",
    infoBorder: "#BCD4E8",
    warning: "#9A5A10",
    warningSoft: "#FFF3E3",
    switchOn: "#C0326B",
    switchOff: "#F0B0CC",
    overlay: "rgba(20,4,12,0.42)",
    shadow: "#2A0D1C",
  },
  dark: {
    // primary: "#8E76E8",
    // primaryStrong: "#654BC3",
    // accent: "#E9C46A",
    // rose: "#E8809F",
    // roseSoft: "#4A2D3A",
    // screenBg: "#120F22",
    // surfaceBg: "#1D1732",
    // elevatedBg: "#251D40",
    // border: "#3A2F5C",
    // text: "#F2EDFF",
    // subtext: "#C3B8E4",
    // muted: "#9388BA",
    // pressedBg: "#322957",
    // headerBtnBg: "#2A204A",
    // switchOn: "#8E76E8",
    // switchOff: "#4A3F70",
    // tint: "#8E76E8",
    // onPrimary: "#FFFFFF",
    // danger: "#F87171",
    // dangerSoft: "#3E2329",
    // dangerBorder: "#7F323D",
    // success: "#5AE19A",
    // successSoft: "#203D31",
    // successBorder: "#2D6B4D",
    // info: "#8CD0F6",
    // infoSoft: "#183652",
    // infoBorder: "#2C5D85",
    // warning: "#F3BD7C",
    // warningSoft: "#3B2D1D",
    // overlay: "rgba(7, 4, 18, 0.66)",
    // shadow: "#090614",

    // dark palette — Rose & Champagne
    primary: '#F07AAA',
    primaryStrong: '#C04478',
    accent: '#F0C0A0',
    rose: '#E8809F',
    roseSoft: '#4A2D3A',
    screenBg: '#180810',
    surfaceBg: '#261022',
    elevatedBg: '#341830',
    border: '#5A2440',
    text: '#FFE8F0',
    subtext: '#E0A8C0',
    muted: '#A87090',
    pressedBg: '#44203A',
    headerBtnBg: '#2A1A26',
    icon: '#E0A8C0',
    onPrimary: '#FFFFFF',
    tint: '#F07AAA',
    danger: '#F07070',
    dangerSoft: '#3D2022',
    dangerBorder: '#7F323D',
    success: '#50D090',
    successSoft: '#183028',
    successBorder: '#2D6B4D',
    info: '#70C0F0',
    infoSoft: '#102840',
    infoBorder: '#2C5D85',
    warning: '#F0B060',
    warningSoft: '#302010',
    switchOn: '#F07AAA',
    switchOff: '#5A2A44',
    overlay: 'rgba(12,2,8,0.66)',
    shadow: '#0C0208',
  },
} as const;

export const ThemeColors = {
  light: {
    text: AppPalettes.light.text,
    background: AppPalettes.light.screenBg,
    tint: AppPalettes.light.tint,
    icon: AppPalettes.light.subtext,
    tabIconDefault: AppPalettes.light.muted,
    tabIconSelected: AppPalettes.light.tint,
  },
  dark: {
    text: AppPalettes.dark.text,
    background: AppPalettes.dark.screenBg,
    tint: AppPalettes.dark.tint,
    icon: AppPalettes.dark.subtext,
    tabIconDefault: AppPalettes.dark.muted,
    tabIconSelected: AppPalettes.dark.tint,
  },
} as const;

export const Colors = ThemeColors;

export const Fonts = Platform.select({
  ios: {
    /** iOS `UIFontDescriptorSystemDesignDefault` */
    sans: "system-ui",
    /** iOS `UIFontDescriptorSystemDesignSerif` */
    serif: "ui-serif",
    /** iOS `UIFontDescriptorSystemDesignRounded` */
    rounded: "ui-rounded",
    /** iOS `UIFontDescriptorSystemDesignMonospaced` */
    mono: "ui-monospace",
  },
  default: {
    sans: "normal",
    serif: "serif",
    rounded: "normal",
    mono: "monospace",
  },
  web: {
    sans: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    serif: "Georgia, 'Times New Roman', serif",
    rounded:
      "'SF Pro Rounded', 'Hiragino Maru Gothic ProN', Meiryo, 'MS PGothic', sans-serif",
    mono: "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
  },
});

export const Spacing = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 24,
  xxl: 32,
} as const;

export const Radius = {
  sm: 6,
  md: 10,
  lg: 14,
  xl: 20,
  pill: 999,
} as const;

export const Theme = {
  colors: Colors,
  appPalettes: AppPalettes,
  fonts: Fonts,
  spacing: Spacing,
  radius: Radius,
} as const;
